spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: associado
        generate_statistics: false
        format_sql: true
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7432/dbassociado?currentSchema=associado
    username: "user_associado"
    password: "user_associado"
    hikari:
      maximum-pool-size: 10
      max-lifetime: 300000
  flyway:
    enabled: true
    table: FLYWAY_SCHEMA_HISTORY
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    placeholders:
      SCHEMA_NAME: associado
      APP_USER: ${spring.datasource.username}
  #    clean-on-validation-error: on
  #    clean-disabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queue:
    consume: "associado.cart.out"

management:
  endpoints:
    web:
      exposure:
        include: "*"

cors:
  allowedOrigins: '*'

server:
  port: 8082
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 100MB
    connection-timeout: 6000

logging:
  file:
    name: @project.artifactId@.log
    path: @project.basedir@
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.stat: DEBUG
#    br.com.poupex.ffa.adminstration.api: DEBUG
#    org.flywaydb: TRACE
#    org.flywaydb.core.internal.dbsupport.SqlScript: TRACE

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: pucminas
  resource: associado-api
  public-client: true
  use-resource-role-mappings: true
  credentials:
    secret: 3ztzCn4mnSF4NQMB3onMBPyVeTmGBNs7

